### ISSUE TITLE
wrong "always use table aliases" issue

### ISSUE THREAD

**Issue by dc55028** [Trivadis/cop-validators#4]
Using PL/SQL Cop for SQLDev v2.2.0, in a query that defines result columns as NULL, I get an issue G-3120 "Always use table aliases when your SQL statement involves more than one source."

For example :
```
  PROCEDURE cop_test(cur_out OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN cur_out FOR
    SELECT a.company_code
         , a.company_name
         , b.contact_name
         , NULL as extra_info
    FROM companies a
      JOIN company_contacts b ON a.id = b.company_id;
  END cop_test;
```
gives me a G-3120 ln the extra_info line.

**Comment by PhilippSalvisberg** [comment]
Thanks for reporting this issue. 

This is a validator bug. Since the parser works without access to the database there will be always some false positives (e.g. when referring a global constant of another package or a standalone function without parameter). However, there are some exceptions we plan to handle, like `SYSDATE`. `NULL` should be handled as well. I've opened  a corresponding [issue]( https://itracker.trivadis.com/issuetracker/browse/PLSQLCOP-259) in our private ticketing system. Should be fixed in the next release.

**Comment by dc55028** [comment]
great :)

for Oracle keywords, you can also add rownum and systimestamp to the list.
I noticed it also tells me to prefix local variables used in the selected columns.

**Comment by sanjaypal943** [comment]
TrivadisGuidelines is not working in my sql developer what can i do for it.?

**Comment by PhilippSalvisberg** [comment]
Please open a new issue and describe what you've done and what does not work. Screenshots may help as well. Thanks.

**Comment by PhilippSalvisberg** [comment]
Fixed. Will not require a table alias for

- `SYSDATE`
- `SYSTIMESTAMP`
- `NULL`
- `LEVEL`
- `ROWNUM`
- `CONNECT_BY_ISLEAF`

Will be part of next release.
